-- AlterTable
ALTER TABLE `LeaveType` ADD COLUMN `creditSchedule` VARCHAR(191) NOT NULL DEFAULT 'ANNUAL',
    ADD COLUMN `eligibleTypes` VARCHAR(191) NOT NULL DEFAULT 'ALL',
    ADD COLUMN `maxCarryForward` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `maxEncashment` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `requiresDocAfterDays` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `employeeType` VARCHAR(191) NOT NULL DEFAULT 'FULL_TIME',
    ADD COLUMN `joiningDate` DATETIME(3) NULL;
