export const USER_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
} as const;

export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  MAX_HOURS_EXCEEDED: 'MAX_HOURS_EXCEEDED',
  BACKDATING_NOT_ALLOWED: 'BACKDATING_NOT_ALLOWED',
  DESCRIPTION_REQUIRED: 'DESCRIPTION_REQUIRED',
  COPY_WEEK_DISABLED: 'COPY_WEEK_DISABLED',
  SELF_MANAGER_ASSIGNMENT: 'SELF_MANAGER_ASSIGNMENT',
  INSUFFICIENT_LEAVE_BALANCE: 'INSUFFICIENT_LEAVE_BALANCE',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  OVERLAPPING_LEAVE: 'OVERLAPPING_LEAVE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  OAUTH_PROVIDER_ERROR: 'OAUTH_PROVIDER_ERROR',
  SSO_DISABLED: 'SSO_DISABLED',
  FORBIDDEN: 'FORBIDDEN',
  OAUTH_PROVIDER_CONFLICT: 'OAUTH_PROVIDER_CONFLICT',
  SELF_APPROVAL_FORBIDDEN: 'SELF_APPROVAL_FORBIDDEN',
  IMMUTABLE_TIMESHEET: 'IMMUTABLE_TIMESHEET',
  NOT_DIRECT_REPORT: 'NOT_DIRECT_REPORT',
  EMPLOYEE_NOT_ASSIGNED: 'EMPLOYEE_NOT_ASSIGNED',
  LEAVE_NOT_CANCELLABLE: 'LEAVE_NOT_CANCELLABLE',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_ERROR: 500,
} as const;

export const TIMESHEET_STATUS = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export const APPROVAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const NOTIFICATION_TYPES = {
  TS_SUBMITTED: 'ts_submitted',
  TS_APPROVED: 'ts_approved',
  TS_REJECTED: 'ts_rejected',
  TS_REMINDER: 'ts_reminder',
  LEAVE_SUBMITTED: 'leave_submitted',
  LEAVE_APPROVED: 'leave_approved',
  LEAVE_REJECTED: 'leave_rejected',
  LEAVE_CANCELLED: 'leave_cancelled',
} as const;

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
